default_platform(:ios)

platform :ios do
  desc "upload dev ipa to Firebase App Distribution"
  lane :upload_to_firebase_dev do
    firebase_app_distribution(
      app: ENV['FIREBASE_IOS_APP_ID'],
      ipa_path: ENV['IPA_PATH'],
      groups: ENV['FIREBASE_APP_DISTRIBUTION_GROUPS'] || "testers",
      release_notes: ENV['RELEASE_NOTES'] || "Dev Build",
      service_credentials_file: ENV['FIREBASE_APP_DISTRIBUTION_KEY_PATH']
    )
  end

  desc "upload prod ipa to Firebase App Distribution"
  lane :upload_to_firebase_prod do
    firebase_app_distribution(
      app: ENV['FIREBASE_IOS_APP_ID'],
      ipa_path: ENV['IPA_PATH'],
      groups: ENV['FIREBASE_APP_DISTRIBUTION_GROUPS'] || "testers",
      release_notes: ENV['RELEASE_NOTES'] || "Prod Build",
      service_credentials_file: ENV['FIREBASE_APP_DISTRIBUTION_KEY_PATH']
    )
  end
end